### ISSUE TITLE
multiple of the same characters get limited to one

### ISSUE THREAD

**Issue by therealprocyon** [hackzone/cz20-badge#10]
I used the keyboard function by copying the cybertyper code and adapting it, but when I type multiple of the same character after each other, it gets limited to one.

**Comment by tjclement** [comment]
I can reproduce this: hid.py:keyboard_type does not flush explicit key up events after each character

**Comment by tjclement** [comment]
Fixed. Will get pushed in the next firmware update. Thanks for reporting!
