### ISSUE TITLE
TTS loop even when having a metadata.json

### ISSUE THREAD

**Issue by therealprocyon** [hackzone/cz20-badge#11]
I have a metadata.json set, as well as made my own app, but it becomes a buggy name and the tts keeps looping...

**Comment by tjclement** [comment]
Do any errors shop up in the terminal during the loop?

**Comment by therealprocyon** [comment]
`[0;37;40mStarting app 'launcher'...
 Preparing TTS:  Animal Crossing
TTS: Success
Preparing TTS:  Animal Crossing
Starting app 'launcher'...
Starting app 'ACFAQ'...
key event
i2c read error [Errno 5] EIO
key event
i2c read error [Errno 5] EIO`

**Comment by tjclement** [comment]
Interesting, so even though the TTS download succeeds, it tries to download it again afterwards. Do you have /flash/cache/appnames/animal_crossing.mp3 in your file system?

**Comment by therealprocyon** [comment]
No, it's named ACFAQ.mp3

**Comment by therealprocyon** [comment]
On windows it says "This file isn't playable. That might be because the file type is unsupported, the file extension is incorrect, or the file is corrupt." And it's corrupted

**Comment by tjclement** [comment]
Yeah downloading mp3 files as a zip in the web interface currently corrupts them somehow. We should log that as a separate issue; perhaps you would be kind enough to do it?

As for the TTS: does /flash/apps/ACFAQ/metadata.json exist? Note that the app "slug" name is case sensitive here

**Comment by therealprocyon** [comment]
yeah it exists, apparently it generates as .MP3 with caps...

**Comment by therealprocyon** [comment]
Wait, slug is missing

**Comment by therealprocyon** [comment]
lemme check again

**Comment by therealprocyon** [comment]
still nothing

**Comment by therealprocyon** [comment]
has to do wiith it generating an all-caps filename

**Comment by therealprocyon** [comment]
it generates all caps and then doesn't work when the slug is in all-caps. So, setting it to acfaq generated acfaq.mp3 instead of ACFAQ.MP3 then it worked

**Comment by tjclement** [comment]
Cheers! Should be fixed in firmware 2104 (uploading, should be available in ~10 mins). Could you check if it works and close the issue if it does?

**Comment by therealprocyon** [comment]
sure

**Comment by therealprocyon** [comment]
fixed, can be closed
