### ISSUE TITLE
Bootloop: "Generating a spoken name for app"

### ISSUE THREAD

**Issue by D3xtar** [hackzone/cz20-badge#13]
Badge runs into a bootloop, and keeps repeating " Generating a spoken name for app" , following a short beep which seems to be caused by the reboot that follows.

Actions that have been done that could possibly triggered this bootloop:

-Updated to the newest firmware
-Installed/Deinstalled some apps from the store,
-Made a test-app through the web-interface. Manually made some directories and files in the "Apps" -folder.
-Moved around some buttons.

All apps have been removed, but the problem persists. Apps are bootable when you press the button right before the spoken message.

Terminal output:
![88153718-11e03d80-cc06-11ea-8723-78aa6481f549](https://user-images.githubusercontent.com/49288804/88202480-3a3d5b80-cc49-11ea-8c5d-8f419d52625c.jpg)

**Comment by D3xtar** [comment]
Update: Removed SD card and booted. Spoken name is now generated correctly! After reinserting the SD still no errors.

**Comment by tjclement** [comment]
Fascinating, thanks for reporting. I'll try to reproduce this later

**Comment by jorisplusplus** [comment]
Disabling Use interrupt for MPI operations seems to fix the bootloop and will generate the tts files while sd card is present. Impact of this change is unknown

**Comment by tjclement** [comment]
Testing now

**Comment by tjclement** [comment]
Fixed in firmware 2205! Please reopen the issue if you're still having trouble
