### ISSUE TITLE
Reboots when starting app launcher (or other apps)

### ISSUE THREAD

**Issue by D3xtar** [hackzone/cz20-badge#14]
After creating/deleting some files in the Apps folder, the launcher app crashes. Terminal shows the following output:

`BADGE.TEAM
Starting app 'launcher'...
>>> assertion "0 && "fatfs internal error"" failed: file "/Users/tom/Git/cz20-badge/firmware-ESP32/esp-idf/components/fatfs/src/vfs_fat.c", line 251, function: fresult_to_errno
abort() was called at PC 0x40119cdb on core 1

Backtrace: 0x4009318f:0x3ffc0bc0 0x40093489:0x3ffc0be0 0x40119cdb:0x3ffc0c00 0x4018777c:0x3ffc0c30 0x40187a4a:0x3ffc0c50 0x40134e46:0x3ffc0c80 0x4000bdbb:0x3ffc0ca0 0x400017ea:0x3ffc0cc0 0x4010bb51:0x3ffc0ce0 0x40119996:0x3ffc0d00 0x40146754:0x3ffc0d20 0x40145966:0x3ffc0d50 0x40145b06:0x3ffc0d90

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:5192
load:0x40078000,len:9088
ho 0 tail 12 room 4
load:0x40080400,len:6652
entry 0x400806f8
`
This appears every 2 seconds.

Web interface is accessible. Pressing a button to start an app does not start the app..

**Comment by D3xtar** [comment]
Message disppears when removing all apps, bu re-appears when installing an app from the store. Starting apps not possible.

**Comment by D3xtar** [comment]
Also appears when starting other apps:

BADGE.TEAM
Starting app 'qmusic_radio'...
assertion "0 && "fatfs internal error"" failed: file "/Users/tom/Git/cz20-badge/firmware-ESP32/esp-idf/components/fatfs/src/vfs_fat.c", line 251, function: fresult_to_errno
abort() was called at PC 0x40119cdb on core 1

Backtrace: 0x4009318f:0x3ffd59b0 0x40093489:0x3ffd59d0 0x40119cdb:0x3ffd59f0 0x4018777c:0x3ffd5a20 0x40187a4a:0x3ffd5a40 0x40134e46:0x3ffd5a70 0x4000bdbb:0x3ffd5a90 0x400017ea:0x3ffd5ab0 0x4010bb51:0x3ffd5ad0 0x40119996:0x3ffd5af0 0x40146754:0x3ffd5b10 0x40145966:0x3ffd5b40 0x40145b06:0x3ffd5b80

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:5192
load:0x40078000,len:9088
ho 0 tail 12 room 4
load:0x40080400,len:6652
entry 0x400806f8

**Comment by D3xtar** [comment]
In every attemp to start an app this lie always show up:

"fatfs internal error"" failed: file "/Users/tom/Git/cz20-badge/firmware-ESP32/esp-idf/components/fatfs/src/vfs_fat.c",

**Comment by tjclement** [comment]
This looks like the FS got corrupted somehow. Maybe the file allocation table is bad. That's unfortunate, because we don't have an easy way to fix this yet. Let's PM about what to do for you. I'll leave this issue open so others can find it, should they run into the same problem (if you do, please add a message here).

**Comment by D3xtar** [comment]
Restored ESP by reflashing. Thank you!

**Comment by D3xtar** [comment]
After making some new folders/files the problem reappeared:

BADGE.TEAM
Starting app 'qmusic_radio'...
assertion "0 && "fatfs internal error"" failed: file "/Users/tom/Git/cz20-badge/firmware-ESP32/esp-idf/components/fatfs/src/vfs_fat.c", line 251, function: fresult_to_errno
abort() was called at PC 0x40119cdb on core 1

Backtrace: 0x4009318f:0x3ffd59b0 0x40093489:0x3ffd59d0 0x40119cdb:0x3ffd59f0 0x4018777c:0x3ffd5a20 0x40187a4a:0x3ffd5a40 0x40134e46:0x3ffd5a70 0x4000bdbb:0x3ffd5a90 0x400017ea:0x3ffd5ab0 0x4010bb51:0x3ffd5ad0 0x40119996:0x3ffd5af0 0x40146754:0x3ffd5b10 0x40145966:0x3ffd5b40 0x40145b06:0x3ffd5b80

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:5192
load:0x40078000,len:9088
ho 0 tail 12 room 4
load:0x40080400,len:6652
entry 0x400806f8

reflashed  and everything works again.

**Comment by tjclement** [comment]
Can you describe the folders/files? If you're not doing anything crazy, you might have faulty flash storage. If so, we'll arrange something for you.

**Comment by annejan** [comment]
If after reflash no more issues . . then that's it . .

If you continue to experience issues . . you'll need a replacement board / ESP 😉 
If so . . please re-open issue or contact @tjclement
