### ISSUE TITLE
Apps fail to update

### ISSUE THREAD

**Issue by xesxen** [hackzone/cz20-badge#15]
The WebUSB environment tries to create the paths it needs when installing an app (https://github.com/hackzone/cz20-badge/blob/master/webusb_site/src/components/Apps.vue#L221). When updating, this isn't needed.

As it currently doesn't take this into account, the Javascript promise will fail which results in the vue component ending up in an improper state (you cannot install anymore apps till you refresh).

**Comment by tjclement** [comment]
This fix will be pushed momentarily (together with progress bar update)

**Comment by tjclement** [comment]
Fixed
