### ISSUE TITLE
[Feature request] Adding optional settings fields in the "Configure home screen buttons"

### ISSUE THREAD

**Issue by MrDiba** [hackzone/cz20-badge#16]
I have build the MQTT button app where the user needs to enter information (MQTT server IP, and topic) in the code before the application can be used.

It would be great if the user can enter the information on the "configure home screen buttons" and that it is parsed over to the application. I do not know if it is (technically) possible or not, but I would like to throw the suggestion.

The idea is that the app creator can add fields (text boxes, radio buttons, ...) to the selected app in the "configure home screen buttons" view. A placeholder variable can be placed in the Python code in the app, and when information is entered in the field the data will be parsed to the variable in the Python code.

**Comment by tjclement** [comment]
Wonderful idea, and already implemented! 😁 https://docs.badge.team/esp32-app-development/api-reference/appconfig/

This adds per-app boxes to the Settings page after your app first runs:
![image](https://user-images.githubusercontent.com/5928359/88221304-9661a900-cc64-11ea-954c-9020e5dbffaf.png)
