### ISSUE TITLE
New Python terminal backspace issue

### ISSUE THREAD

**Issue by tjclement** [hackzone/cz20-badge#20]
In Paste Mode (which you enter with CTRL+E), pressing backspace does not remove the character left of the caret. Outside of paste mode, this works fine.

**Comment by jorisplusplus** [comment]
It looks like doing backspace in the serial terminal sends char code 8 while doing it in the terminal on the website it sends code 127. This also generates a parsing error on xterm.js

Ctrl+H seems to be doing the desired effect

**Comment by xesxen** [comment]
Screen also is sending 0x7B as the backspace. In paste mode it shows the same behaviour, but imho this is fair as you're pasting content. It's not an editor.

Mitigating this by replacing 0x7B by `\b \b` also gives undesired behaviour as you can now backspace further than the content you've typed/pasted in. 

I personally wouldn't fix this as it behaves as intended
